### ISSUE TITLE
More React/Vue practical examples?

### ISSUE THREAD

**Issue by vikkio88** [radonjs/Radon#51]
Hi, amazing work in here, it looks really promising.
Just one small thing though, the documentation on the Readme is too verbose and it is, imho, missing an example of Component that uses a piece of state from a silo.
You can see how to trigger a mutation, but not how to pass that piece of state to the component, let's say the equivalent of `connect()` on Redux.

**Comment by G0ldenSp00n-zz** [comment]
Hi,
Components are connected to the state using `bindToSilo()` and the automatic attach to the piece of state labeled ComponentName + State.  So as an example if I wanted the state of my App component I would export it using `bindToSilo(App)` which would automatically give it the state of the SiloNode labels AppState.

We have a better breakdown of all of this on our website, [http://radonjs.org](http://radonjs.org) with more concrete examples to follow along with.

Let me know if you think the website's documentation is clear enough,
Hayden

**Comment by vikkio88** [comment]
@G0ldenSp00n that is nice to see, wonderful docs in there, I would that example in the readme, and why you dont like the website on the repo?

**Comment by G0ldenSp00n-zz** [comment]
Yeah, will definitely add that link to the readme, so that people can quickly find the documentation.

Thanks for the suggestion,
Hayden

**Comment by vikkio88** [comment]
if you want @G0ldenSp00n I could put up a PR about how I think the mini-doc in the readme should be simplified to showcase in an easier way how to use it, rather than "how it works".

That would be way better from a user perspective imho

**Comment by G0ldenSp00n-zz** [comment]
Sounds great, go ahead and make a PR with how you think the readme should be.

**Comment by vikkio88** [comment]
could you assign this issue to me? @G0ldenSp00n so I can remember to do it between tomorrow and monday?

**Comment by G0ldenSp00n-zz** [comment]
Done

**Comment by ntsmitty** [comment]
Hi @vikkio88 ,

About the Vue bindings, they are still being worked on. We hope to have them completed soon.

**Comment by vikkio88** [comment]
hey @ntsmitty to be honest with you I do not use vue that much nowadays, like the rest of the world :smile:  I wanted to copy paste the examples on the readme for new comers, I think I will do it now

**Comment by vikkio88** [comment]
opened a small pr #53 
@G0ldenSp00n by repo link I meant in here 
![image](https://user-images.githubusercontent.com/248805/46888833-87c44c00-ce59-11e8-8256-e467fa1d4cad.png)

**Comment by G0ldenSp00n-zz** [comment]
Alright, I added it to the Website link at the top of the repo.
